<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sponsorship Agreement</title>
    <style>
        body { font-family: sans-serif; padding: 40px; color: #333; line-height: 1.6; }
        h1 { text-align: center; color: #2C3E50; margin-bottom: 50px; }
        .details { margin-bottom: 40px; }
        .details th { text-align: left; padding-right: 20px; color: #7F8C8D; }
        .content { margin-top: 30px; border-top: 1px solid #BDC3C7; padding-top: 30px; }
        .signatures { margin-top: 80px; width: 100%; display: table; }
        .signature-box { display: table-cell; width: 50%; }
        .line { border-bottom: 1px solid #333; width: 80%; margin-top: 40px; margin-bottom: 10px; }
    </style>
</head>
<body>

    <h1>Official Sponsorship Agreement</h1>

    <table class="details">
        <tr><th>Agreement Date:</th><td>{{ $date }}</td></tr>
        <tr><th>Event Title:</th><td><strong>{{ $event->title }}</strong></td></tr>
        <tr><th>Event Date:</th><td>{{ \Carbon\Carbon::parse($event->start_time)->format('F j, Y, g:i a') }}</td></tr>
        <tr><th>Venue:</th><td>{{ $event->venue->name ?? 'TBD' }}</td></tr>
    </table>

    <div class="content">
        <p>This agreement is made between <strong>{{ $manager->name }}</strong> (Event Manager) and <strong>{{ $sponsor->name }}</strong> (Sponsor).</p>
        
        <p>By accepting the sponsorship request on the EventHub platform, both parties agree to collaborate on the event <strong>{{ $event->title }}</strong>.</p>
        
        <h3>Terms & Conditions:</h3>
        <ul>
            <li>The Sponsor agrees to provide the agreed-upon support for the event.</li>
            <li>The Event Manager agrees to fulfill all promotional obligations associated with this sponsorship.</li>
            <li>This document is automatically generated by EventHub as proof of the digital agreement between both parties.</li>
        </ul>
    </div>

    <div class="signatures">
        <div class="signature-box">
            <p><strong>Event Manager</strong></p>
            <div class="line"></div>
            <p>{{ $manager->name }}</p>
        </div>
        <div class="signature-box">
            <p><strong>Sponsor</strong></p>
            <div class="line"></div>
            <p>{{ $sponsor->name }}</p>
        </div>
    </div>

</body>
</html>
